// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpN92e7K6dHlyHn0NW_MvzSk52gHbeylg',
    appId: '1:251517331715:web:c9b37c734b9377ec73e136',
    messagingSenderId: '251517331715',
    projectId: 'instagram-clone-469d2',
    authDomain: 'instagram-clone-469d2.firebaseapp.com',
    storageBucket: 'instagram-clone-469d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgIsEDBmOdxSECBmp1YoCVBxOxmvXjBA8',
    appId: '1:251517331715:android:86d6380efedf7e0373e136',
    messagingSenderId: '251517331715',
    projectId: 'instagram-clone-469d2',
    storageBucket: 'instagram-clone-469d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg6wBGiRPs7Hx9oCsMETgAsiZ5zgB7AdI',
    appId: '1:251517331715:ios:f76a2287476dc33973e136',
    messagingSenderId: '251517331715',
    projectId: 'instagram-clone-469d2',
    storageBucket: 'instagram-clone-469d2.appspot.com',
    iosClientId: '251517331715-pmvj2p1npp7t0fcf6tm6082vt9ma8220.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg6wBGiRPs7Hx9oCsMETgAsiZ5zgB7AdI',
    appId: '1:251517331715:ios:85fbb264edc3bb2473e136',
    messagingSenderId: '251517331715',
    projectId: 'instagram-clone-469d2',
    storageBucket: 'instagram-clone-469d2.appspot.com',
    iosClientId: '251517331715-51cqvnhbe2ccft3cspvna3p7p0596go4.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
